// P1 — self-host fonts properly.
// Google returns every language subset (17 files, 410 KB). We keep only
// latin + latin-ext, download each file under its real name, and rewrite
// every url() to a local path. Also dedupes byte-identical @font-face blocks.
import { writeFile, readFile, readdir, unlink, mkdir, stat } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve('..');
const FDIR = path.join(ROOT, '2026', 'assets', 'fonts');
const CSS = path.join(ROOT, '2026', 'assets', 'css', 'fonts.css');
await mkdir(FDIR, { recursive: true });

// NOTE: the fonts already on disk are NOT deleted up front. An earlier version
// started clean, and a fetch that failed halfway left fonts.css pointing at
// files that had just been removed — a broken page from a build step that was
// only supposed to be additive. Stale files are now swept at the END, once the
// new stylesheet is on disk.

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Four faces, four jobs — see tokens.css for the usage rules.
//   Cormorant Garamond — the romantic voice (quotes, the letter, signatures)
//   Fredoka            — the cute voice (headings, labels, buttons, numbers)
//   Caveat             — the handwritten voice (love notes, margin asides)
//   Inter              — the plain voice (body copy, captions, meta)
const SRC = 'https://fonts.googleapis.com/css2'
  + '?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500'
  + '&family=Fredoka:wght@400;500;600'
  + '&family=Caveat:wght@400;600'
  + '&family=Inter:wght@300;400;500;600'
  + '&display=swap';

const css = await (await fetch(SRC, { headers: { 'user-agent': UA } })).text();
if (!css.includes('@font-face')) {
  console.error('FAIL: Google returned no @font-face blocks. Body was:\n' + css.slice(0, 400));
  process.exit(1);
}

const KEEP = new Set(['latin', 'latin-ext']);
const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .filter((b) => KEEP.has(b[1]));

console.log(`${blocks.length} @font-face blocks in latin/latin-ext (of ${[...css.matchAll(/@font-face/g)].length} total)`);

const seen = new Map();   // url -> local filename
const out = [];
const meta = [];          // family/style/subset/file, for the preload hints
let downloaded = 0;

for (const [, subset, block] of blocks) {
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  if (!seen.has(url)) {
    const name = path.basename(new URL(url).pathname);
    const res = await fetch(url, { headers: { 'user-agent': UA } });
    await writeFile(path.join(FDIR, name), Buffer.from(await res.arrayBuffer()));
    seen.set(url, name);
    downloaded++;
  }

  meta.push({
    family: block.match(/font-family:\s*'([^']+)'/)?.[1],
    style:  block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal',
    subset,
    file: seen.get(url),
  });

  // rewrite to a local relative path and record the subset for the comment
  const local = block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(../fonts/${seen.get(url)})`);
  const key = local.replace(/\s+/g, ' ');
  if (out.some((o) => o.key === key)) continue;   // dedupe identical blocks
  out.push({ key, text: `/* ${subset} */\n${local}` });
}

const header = `/* Self-hosted Cormorant Garamond + Fredoka + Caveat + Inter — latin & latin-ext only.
   Full Google multi-subset set was 410 KB across 17 files; this is ${seen.size} files.
   Generated by tools/p1-fonts.mjs — re-run it rather than hand-editing.

   Four families, four jobs. Do not use a face outside its job, or the page
   starts to read as assembled rather than designed:
     Cormorant Garamond  the romantic voice — quotes, the letter, signatures
     Fredoka             the cute voice     — headings, labels, buttons, numbers
     Caveat              the handwritten voice — love notes, margin asides
     Inter               the plain voice    — body copy, captions, meta */\n\n`;
await writeFile(CSS, header + out.map((o) => o.text).join('\n\n') + '\n');

/* ---------------------------------------------------- the preload hints
   index.html preloads two of the files, and a preload pointing at a hash that
   no longer exists is worse than no preload: it is a wasted request plus a
   console error, and it silently stops warming the font it was meant to warm.
   The hashes are Google's and they move when Google re-cuts a face, so the
   script that downloads the files writes the hints rather than a human. */
const FAMILIES = ['Cormorant Garamond', 'Fredoka', 'Caveat', 'Inter'];
const missing = FAMILIES.filter((f) => !meta.some((m) => m.family === f));
if (missing.length) {
  console.error(`\nFAIL: no @font-face for ${missing.join(', ')}. The CSS names these`);
  console.error('families in tokens.css, so the page would silently fall back.');
  process.exit(1);
}

const latinFile = (family) =>
  meta.find((m) => m.family === family && m.subset === 'latin' && m.style === 'normal')?.file;

const HTML = path.join(ROOT, '2026', 'index.html');
const html = await readFile(HTML, 'utf8');
const preload = FAMILIES
  .map(latinFile)
  .filter(Boolean)
  .slice(0, 2)
  .map((f) => `<link rel="preload" href="./assets/fonts/${f}" as="font" type="font/woff2" crossorigin>`)
  .join('\n');

const marked = /<!-- fonts:start -->[\s\S]*?<!-- fonts:end -->/;
if (!marked.test(html)) {
  console.warn('\nwarn: no <!-- fonts:start --> block in index.html — preload hints not updated');
} else {
  const next = html.replace(marked, `<!-- fonts:start -->\n${preload}\n<!-- fonts:end -->`);
  if (next !== html) { await writeFile(HTML, next); console.log('\npreload hints rewritten in index.html'); }
  else console.log('\npreload hints already correct');
}

// Sweep only now, with the new stylesheet AND the new hints already on disk:
// anything they do not name is an orphan from a previous run. A failed fetch
// above means this line never runs, so the old fonts and the old stylesheet are
// never left disagreeing. The hints are rewritten just above, so a file that
// Google re-hashed is already out of index.html by the time we get here.
const keep = new Set(seen.values());
for (const f of await readdir(FDIR)) {
  if (!keep.has(f)) {
    await unlink(path.join(FDIR, f));
    console.log(`  removed orphan ${f}`);
  }
}

let total = 0;
for (const f of (await readdir(FDIR)).sort()) {
  const s = await stat(path.join(FDIR, f));
  total += s.size;
  console.log(`  ${f.padEnd(42)} ${(s.size / 1024).toFixed(1)} KB`);
}
console.log(`\ndownloaded ${downloaded} files, wrote ${out.length} @font-face rules`);
console.log(`font payload: ${(total / 1024).toFixed(0)} KB`);

// fail loudly rather than shipping a stylesheet pointing at gstatic
if ((await readFile(CSS, 'utf8')).includes('https://fonts.gstatic.com')) {
  console.error('\nFAIL: fonts.css still references gstatic — aborting.');
  process.exit(1);
}
console.log('verified: no remote font URLs remain');
