// P1 — self-host fonts properly.
// Google returns every language subset (17 files, 410 KB). We keep only
// latin + latin-ext, download each file under its real name, and rewrite
// every url() to a local path. Also dedupes byte-identical @font-face blocks.
import { writeFile, readdir, unlink, mkdir, stat } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve('..');
const FDIR = path.join(ROOT, '2026', 'assets', 'fonts');
const CSS = path.join(ROOT, '2026', 'assets', 'css', 'fonts.css');
await mkdir(FDIR, { recursive: true });

// start clean so a previous bad run can't leave orphans
for (const f of await readdir(FDIR)) await unlink(path.join(FDIR, f));

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const SRC = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300&family=Inter:wght@300;400;500&display=swap';

const css = await (await fetch(SRC, { headers: { 'user-agent': UA } })).text();

const KEEP = new Set(['latin', 'latin-ext']);
const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .filter((b) => KEEP.has(b[1]));

console.log(`${blocks.length} @font-face blocks in latin/latin-ext (of ${[...css.matchAll(/@font-face/g)].length} total)`);

const seen = new Map();   // url -> local filename
const out = [];
let downloaded = 0;

for (const [, subset, block] of blocks) {
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  if (!seen.has(url)) {
    const name = path.basename(new URL(url).pathname);
    const res = await fetch(url, { headers: { 'user-agent': UA } });
    await writeFile(path.join(FDIR, name), Buffer.from(await res.arrayBuffer()));
    seen.set(url, name);
    downloaded++;
  }

  // rewrite to a local relative path and record the subset for the comment
  const local = block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(../fonts/${seen.get(url)})`);
  const key = local.replace(/\s+/g, ' ');
  if (out.some((o) => o.key === key)) continue;   // dedupe identical blocks
  out.push({ key, text: `/* ${subset} */\n${local}` });
}

const header = `/* Self-hosted Cormorant Garamond + Inter — latin & latin-ext only.
   Full Google multi-subset set was 410 KB across 17 files; this is ${seen.size} files.
   Generated by tools/p1-fonts.mjs — re-run it rather than hand-editing. */\n\n`;
await writeFile(CSS, header + out.map((o) => o.text).join('\n\n') + '\n');

let total = 0;
for (const f of (await readdir(FDIR)).sort()) {
  const s = await stat(path.join(FDIR, f));
  total += s.size;
  console.log(`  ${f.padEnd(42)} ${(s.size / 1024).toFixed(1)} KB`);
}
console.log(`\ndownloaded ${downloaded} files, wrote ${out.length} @font-face rules`);
console.log(`font payload: ${(total / 1024).toFixed(0)} KB (was 410 KB)`);

// fail loudly rather than shipping a stylesheet pointing at gstatic
const css2 = await import('node:fs/promises').then((m) => m.readFile(CSS, 'utf8'));
if (css2.includes('https://fonts.gstatic.com')) {
  console.error('\nFAIL: fonts.css still references gstatic — aborting.');
  process.exit(1);
}
console.log('verified: no remote font URLs remain');
